-------------------- LOG 2025-09-11 15:42:32.860843 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-11 15:42:40.339752 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-11 15:43:11.238591 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-11 15:43:22.829421 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-20 23:56:45.591740 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
LOG: python path: E:\divelop\Game-Engine-3/python/python.exe
-------------------- LOG 2025-09-20 23:58:12.381664 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-21 00:01:25.903087 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-21 00:01:36.129675 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-21 00:01:58.879031 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-22 16:43:30.155765 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
LOG: python path: E:\divelop\Game-Engine-3/python/python.exe
-------------------- LOG 2025-09-22 16:55:53.834827 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
LOG: not found image (projects/w/project/assets/player.png)
LOG: not found image (projects/w/project/assets/player.png)
-------------------- LOG 2025-09-22 17:53:57.546950 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-22 17:55:03.830677 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-09-22 17:55:29.034506 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-10 19:21:43.559317 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-13 19:55:32.656412 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-13 23:44:43.704089 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-13 23:44:49.881173 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-13 23:45:02.168690 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
ERROR: can't download now project version, bad internet connection
ERROR: request failed: HTTPSConnectionPool(host='artyom7777.pythonanywhere.com', port=443): Max retries exceeded with url: /updateOnline (Caused by NameResolutionError("<urllib3.connection.HTTPSConnection object at 0x0000022F697F8450>: Failed to resolve 'artyom7777.pythonanywhere.com' ([Errno 11001] getaddrinfo failed)"))
-------------------- LOG 2025-10-13 23:49:54.666110 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-13 23:51:34.497077 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-13 23:51:59.238348 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-13 23:53:32.049358 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-13 23:57:36.149234 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-14 00:00:35.744381 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
-------------------- LOG 2025-10-14 00:03:17.662247 --------------------
LOG: divelop mode = False
LOG: program runned on "Windows 10"
LOG: last version = 3.13.1, now version = 3.13.1
